site_name: Robot Developer Extensions for URDF editing
repo_url: https://github.com/ranch-hand-robotics/rde-urdf
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - IntelliSense: IntelliSense.md
  - Configuration: Configuration.md
  - Xacro Arguments & Environment Variables: xacro-configuration.md
  - WebXR Preview: WebXRPreview.md
  - OpenSCAD: OpenSCAD.md
  - Model Context Protocol: mcp.md
  - Support: Support.md

theme: 
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
use_directory_urls: false
strict: true
